# ~~~~~~~~~~~~~~~~~ Orders ~~~~~~~~~~~~~~~~~
###
GET http://localhost:3000/api/orders/

# Create Order
###
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "order": {
    "totalAmount": "12121.99",
    "product": [
      {
        id: 1,
        amount
      }
    ]
  }
}

# ~~~~~~~~~~~~~~~~~ Products ~~~~~~~~~~~~~~~~~
###
GET https://next-pos-sable.vercel.app/api/products

# Create Products
###
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "product": {
    "name": "asdasd",
    "price": "481.15",
    "quantity": 50
  }
}

# ~~~~~~~~~~~~~~~~~ Users ~~~~~~~~~~~~~~~~~
###
GET https://next-pos-sable.vercel.app/api/users

# Specific User
###
GET https://next-pos-sable.vercel.app/users/48250be6-e0b3-4337-9298-c2b95489e695