###
GET http://localhost:3000/api/orders

###
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "order": {
    "totalAmount": "12121.99",
    "product": [
      {
        id: 1,
        amount
      }
    ]
  }
}

# Products
###
GET http://localhost:3000/api/products

###
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "product": {
    "name": "asdasd",
    "price": "481.15",
    "quantity": 50
  }
}