import Head from 'next/head'
import POSTItemsList from '../components/pos/POSTItemsList'

function classNames(...classes) {
  return classes.filter(Boolean).join(' ')
}

export default function Home() {
  return (
    <div className="bg-white">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <main>
          <POSTItemsList />
        </main>

        <footer className="bg-gray-50" aria-labelledby="footer-heading">

        </footer>
      </div>
    </div>
  )
}
